CREATE TABLE delivery_tracking
(
    driver_id       bigint,
    session_id      bigint,
    recorded_at     timestamp with time zone,
    app_duration    numeric(6, 2),
    device_duration numeric(10, 2),
    device_name     text,
    tracking_type   text,
    battery_status  text,
    gps_location    point,
    log_id          bigint,
    sim_imsi        character(15),
    connection_time timestamp with time zone,
    network_id      character varying(6),
    sync_method     character(1),
    app_version     character varying(6)
);

INSERT INTO delivery_tracking (driver_id,
                               session_id,
                               recorded_at,
                               app_duration,
                               device_duration,
                               device_name,
                               tracking_type,
                               battery_status,
                               gps_location,
                               log_id,
                               sim_imsi,
                               connection_time,
                               network_id,
                               sync_method,
                               app_version)
SELECT trunc(random() * 1000 + 1)::bigint                                     AS driver_id,
       trunc(random() * 10000 + 1)::bigint                                    AS session_id,
       now() - (interval '1 day' * (random() * 30))                           AS recorded_at,
       trunc(random() * 60 + 1)::numeric(6, 2)                                AS app_duration,
       trunc(random() * 1000 + 1)::numeric(10, 2)                             AS device_duration,
       ('Device_' || trunc(random() * 10 + 1))::text                          AS device_name,
       (ARRAY ['GPS', 'Accelerometer', 'Pedometer'])[floor(random() * 3 + 1)] AS tracking_type,
       trunc(random() * 100 + 1)::smallint                                    AS battery_status,
       point(-180 + random() * 360, -90 + random() * 180)                     AS gps_location,
       trunc(random() * 100000 + 1)::bigint                                   AS log_id,
       lpad(trunc(random() * 999999999999999)::text, 15, '0')                 AS sim_imsi,
       now() - (interval '1 day' * (random() * 30))                           AS connection_time,
       trunc(random() * 75 + 1)::text                                         AS network_id,
       (ARRAY ['A', 'B', 'C'])[floor(random() * 3 + 1)]                       AS sync_method,
       lpad(trunc(random() * 999999)::text, 6, '0')                           AS app_version
FROM generate_series(1, 250);
